import {  Poppins } from "next/font/google";
import "./globals.css";


const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-poppins",
});



export const metadata = {
  title: "Dragon-news",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      data-theme='light'
      className={`${poppins.className}  h-full antialiased`}
    >
      <body className={` min-h-full flex flex-col`}>
        

        <main>
          {children}
        </main>
        </body>
    </html>
  );
}
